---
all:
  hosts:
    bastion01.sjc1.vexxhost.zuul-ci.ansible.com:
      ansible_host: 38.108.68.114
      ansible_ssh_host_key_ed25519_public: AAAAC3NzaC1lZDI1NTE5AAAAIPVbbkDWEwZkas6hldXONrqO40vO9PdZnuxf8D8oNnmg
      ansible_user: windmill
      node_attributes:
        public_ipv4: 38.108.68.114
        public_ipv6: ''

    borg01.ca-ymq-1.vexxhost.zuul-ci.ansible.com:
      ansible_host: 162.253.55.23
      ansible_ssh_host_key_ed25519_public: AAAAC3NzaC1lZDI1NTE5AAAAIMeiv4sN/0j29kgcV5XCaJknedppNUDc9ggW8ehHg0It
      ansible_user: windmill
      node_attributes:
        public_ipv4: 162.253.55.23
        public_ipv6: 2604:e100:1:0:f816:3eff:fe5a:72fd

    statsd01.sjc1.vexxhost.zuul-ci.ansible.com:
      ansible_host: 38.108.68.117
      ansible_ssh_host_key_ed25519_public: AAAAC3NzaC1lZDI1NTE5AAAAIPkS6ZefSc9bBW7qRAPW364JsJ2DVrQonhs3OaxFMfAI
      ansible_user: windmill
      node_attributes:
        public_ipv4: 38.108.68.117
        public_ipv6: ''

  children:
    bastion:
      hosts:
        bastion01.sjc1.vexxhost.zuul-ci.ansible.com:

    borg:
      children:
        borg-client: {}
        borg-server: {}

    # NOTE(pabelanger): Remember to create borgmatic configuration and
    # encryption_passphrase each time we add a new host to borg-client
    # group.
    borg-client:
      children:
        bastion: {}

    borg-server:
      hosts:
        borg01.ca-ymq-1.vexxhost.zuul-ci.ansible.com:

    # NOTE(pabelanger): Hosts added to the disabled group will not have
    # playbooks run against them.
    disabled: {}

    gear: {}

    nodepool:
      children:
        nodepool-builder: {}
        nodepool-launcher: {}

    nodepool-builder: {}

    nodepool-launcher: {}

    statsd:
      hosts:
        statsd01.sjc1.vexxhost.zuul-ci.ansible.com:

    zookeeper: {}

    zuul:
      children:
        zuul-executor: {}
        zuul-fingergw: {}
        zuul-merger: {}
        zuul-scheduler: {}
        zuul-web: {}

    zuul-connections:
      children:
        zuul-executor: {}
        zuul-merger: {}
        zuul-scheduler: {}

    zuul-executor: {}

    zuul-fingergw: {}

    zuul-merger: {}

    zuul-scheduler: {}

    zuul-web: {}
