---
all:
  hosts:
    bastion01.sjc1.vexxhost.zuul.ansible.com:
      ansible_host: 38.108.68.150
      ansible_ssh_host_key_ed25519_public: AAAAC3NzaC1lZDI1NTE5AAAAIJwUngYI3KGYjZ3kFlX11bo3OS/ZS92wKQGEnIoQjxgS
      ansible_user: windmill
      node_attributes:
        public_ipv4: 38.108.68.150
        public_ipv6: ''

  children:
    bastion:
      hosts:
        bastion01.sjc1.vexxhost.zuul.ansible.com:

    borg:
      children:
        borg-client: {}
        borg-server: {}

    # NOTE(pabelanger): Remember to create borgmatic configuration and
    # encryption_passphrase each time we add a new host to borg-client
    # group.
    borg-client: {}

    borg-server: {}

    # NOTE(pabelanger): We currently only support a single database host in
    # this group.  This means, the first host listed will only be used by our
    # configuration.
    #
    # The host in this group was manually provisioned, this means if we lose
    # this host for any reason, we need to rebuild it by hand. ASAP create
    # ansible playbooks / roles to properly automate this into a fully HA
    # deployment.
    database: {}

    # NOTE(pabelanger): Hosts added to the disabled group will not have
    # playbooks run against them.
    disabled: {}

    # NOTE(pabelanger): We currently only support a single gear host in this
    # group.  This means, the first host listed will only be used by our
    # configuration.
    gear: {}

    nodepool:
      children:
        nodepool-builder: {}
        nodepool-launcher: {}

    nodepool-builder: {}

    nodepool-launcher: {}

    # NOTE(pabelanger): We currently only support a single statsd host in this
    # group.  This means, the first host listed will only be used by our
    # configuration.
    statsd: {}

    zookeeper: {}

    zuul:
      children:
        zuul-executor: {}
        zuul-fingergw: {}
        zuul-merger: {}
        zuul-scheduler: {}
        zuul-web: {}

    zuul-connections:
      children:
        zuul-executor: {}
        zuul-merger: {}
        zuul-scheduler: {}

    zuul-executor: {}

    # NOTE(pabelanger): We currently only support a single zuul-fingergw host
    # in this group.  This means, the first host listed will only be used by
    # our configuration.
    zuul-fingergw: {}

    zuul-merger: {}

    zuul-scheduler: {}

    zuul-web: {}
