- hosts: localhost
  tasks:
    - name: Add bastion server
      add_host:
        name: bastion.poctron.xyz
        ansible_user: ubuntu
        group: bastion

- hosts: bastion
  tasks:
    - name: Synchronize windmill repo
      synchronize:
        dest: ~/src/git.openstack.org/windmill
        src: ~/src/git.openstack.org/windmill
      no_log: true
