- hosts: localhost
  tasks:
    - name: Add bastion server
      add_host:
        name: bastion.poctron.xyz
        ansible_user: ubuntu
        group: bastion

- hosts: bastion
  tasks:
    - name: Synchronize required-project to bastion
      synchronize:
        dest: "{{ ansible_user_dir }}"
        src: ~/src
        rsync_opts:
          - "--exclude=.tox"

    - name: Bootstrap tox environment
      args:
        chdir: ~/src/git.openstack.org/openstack/windmill
      shell: /home/ubuntu/.local/bin/tox -evenv --notest

    - name: Run ansible-playbook for site.yaml
      args:
        chdir: ~/src/git.openstack.org/openstack/windmill
      shell: /home/ubuntu/.local/bin/tox -evenv -- ansible-playbook -v playbooks/site.yaml
